module.exports = function (grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        less: {
            intecmedia: {
                options: {
                    banner: '/*! Generated by Grunt-Contrib-LESS: <%= grunt.template.today("isoDateTime") %> | css/style.less */\r\n',
                    strictMath: true,
                    syncImport: true
                },
                files: {
                    'css/style.min.css': 'css/style.less'
                }
            }
        },
        browserSync: {
            dev: {
                bsFiles: {
                    src : [
                        './css/*.{less,css}', './css/**/*.{less,css}',
                        './js/*.js', './js/**/*.js',
                        './*.{php,html}', './**/*.{php,html}'
                    ]
                },
                options: {
                    watchTask: true,
                    server: './'
                }
            }
        },
        postcss: {
            options: {
                processors: [
                    require('autoprefixer')({
                        browsers: 'last 2 versions'
                    }),
                    require('cssnano')()
                ]
            },
            dist: {
                src: 'css/style.min.css'
            }
        },
        watch: {
            files: ['css/*.less', 'css/**/*.less'],
            tasks: ['less', 'postcss']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-less');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-browser-sync');
    grunt.loadNpmTasks('grunt-postcss');

    grunt.registerTask('default', ['watch']);
    grunt.registerTask('sync', ['browserSync', 'watch']);
};
